# キーバインドvim風に
setw -g mode-keys vi

# 'v' で選択を始める(コピーモードの時)
# 'V'で行選択は効くが、なぜか'v'で選択が効かなかったため
bind -T copy-mode-vi v send -X begin-selection

# 'y' でヤンク（コピー）してコピーモードを終了
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# マウススクロール
set -g mouse on
bind-key -T edit-mode-vi WheelUpPane send-keys -X scroll-down
bind-key -T edit-mode-vi WheelDownPane send-keys -X scroll-up

# クリップボードにコピー
# マウススクロールをオンにすると、マウス選択コピーがクリップボードにコピーされなくなるため
set -s copy-command 'pbcopy' 

# ペイン操作
# "|" でペインを縦分割する
bind | split-window -h -c "#{pane_current_path}"
# "-" でペインを縦分割する
bind - split-window -v -c "#{pane_current_path}"

# ペインの開始番号を 0 から 1 に変更する
set-option -g base-index 1

bind n new-window

# 右側はデフォルト表示
# ペインボーダー
# 太線で描画してアクティブペインを目立たせる
set -g pane-border-lines heavy
set -g pane-active-border-style "fg=cyan"
set -g pane-border-style "fg=colour238"

set -g status-right "%Y-%m-%d %H:%M"

